// <auto-generated />
using System;
using GoalsPlanningSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalsPlanningSystem.Infrastructure.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerGoalsPlanningSystemDbContext))]
    [Migration("20260716094238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal?>("AssumedAnnuityRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ContributionFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EmployerMatchPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NpsAnnuitizationPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AccountAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AssetClassId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("AccountId", "AssetClassId")
                        .IsUnique();

                    b.ToTable("AccountAllocations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualVolatilityPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExpectedAnnualReturnPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetClasses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClassCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetClassAId")
                        .HasColumnType("int");

                    b.Property<int>("AssetClassBId")
                        .HasColumnType("int");

                    b.Property<decimal>("Correlation")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassBId");

                    b.HasIndex("AssetClassAId", "AssetClassBId")
                        .IsUnique();

                    b.ToTable("AssetClassCorrelations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.CapitalGainsRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetCategory")
                        .HasColumnType("int");

                    b.Property<int>("HoldingPeriodMonthsThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("LongTermExemptionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LongTermRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ShortTermRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ShortTermTaxedAtSlabRate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategory")
                        .IsUnique();

                    b.ToTable("CapitalGainsRules");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("LifeExpectancyAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("int");

                    b.Property<int?>("RiskProfile")
                        .HasColumnType("int");

                    b.Property<int?>("RiskProfileOverride")
                        .HasColumnType("int");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int");

                    b.Property<int>("TaxRegime")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeductionsAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrowthRateOverridePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("InflationRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SimulationCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrowthRateOverridePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.GoalAccountLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalAccountLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AnnualGrowthRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<int>("IncomeType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RiskQuestions");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RiskQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RiskQuestionId");

                    b.ToTable("RiskQuestionOptions");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionnaireResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiskQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("RiskQuestionOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskQuestionId");

                    b.HasIndex("RiskQuestionOptionId");

                    b.HasIndex("ClientId", "RiskQuestionId")
                        .IsUnique();

                    b.ToTable("RiskQuestionnaireResponses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.TaxSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CessPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RebateIncomeThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RebateMaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Regime")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardDeduction")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Regime")
                        .IsUnique();

                    b.ToTable("TaxSettings");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.TaxSlab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LowerBound")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Regime")
                        .HasColumnType("int");

                    b.Property<int>("SlabOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("UpperBound")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Regime", "SlabOrder")
                        .IsUnique();

                    b.ToTable("TaxSlabs");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AccountAllocation", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Account", "Account")
                        .WithMany("Allocations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClass")
                        .WithMany("AccountAllocations")
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AssetClass");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClassCorrelation", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClassA")
                        .WithMany()
                        .HasForeignKey("AssetClassAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClassB")
                        .WithMany()
                        .HasForeignKey("AssetClassBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetClassA");

                    b.Navigation("AssetClassB");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Expense", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Expenses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Goals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.GoalAccountLink", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Account", "Account")
                        .WithMany("GoalLinks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Goal", "Goal")
                        .WithMany("AccountLinks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Income", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Incomes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany("Options")
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskQuestion");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionnaireResponse", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("RiskQuestionnaireResponses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany()
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", "RiskQuestionOption")
                        .WithMany()
                        .HasForeignKey("RiskQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("RiskQuestion");

                    b.Navigation("RiskQuestionOption");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("GoalLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClass", b =>
                {
                    b.Navigation("AccountAllocations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Client", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Expenses");

                    b.Navigation("Goals");

                    b.Navigation("Incomes");

                    b.Navigation("RiskQuestionnaireResponses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.Navigation("AccountLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
