// <auto-generated />
using System;
using GoalsPlanningSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalsPlanningSystem.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(SqliteGoalsPlanningSystemDbContext))]
    [Migration("20260717103549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AssumedAnnuityRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContributionFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EmployerMatchPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NpsAnnuitizationPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AccountAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClassId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("AccountId", "AssetClassId")
                        .IsUnique();

                    b.ToTable("AccountAllocations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualVolatilityPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualReturnPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetClasses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClassCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClassAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClassBId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Correlation")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassBId");

                    b.HasIndex("AssetClassAId", "AssetClassBId")
                        .IsUnique();

                    b.ToTable("AssetClassCorrelations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.CapitalGainsRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoldingPeriodMonthsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermExemptionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShortTermRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShortTermTaxedAtSlabRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategory")
                        .IsUnique();

                    b.ToTable("CapitalGainsRules");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("LifeExpectancyAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RiskProfile")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RiskProfileOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxRegime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDeductionsAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrowthRateOverridePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrowthRateOverridePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.GoalAccountLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalAccountLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualGrowthRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflationRatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiskQuestions");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RiskQuestionId");

                    b.ToTable("RiskQuestionOptions");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionnaireResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskQuestionOptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RiskQuestionId");

                    b.HasIndex("RiskQuestionOptionId");

                    b.HasIndex("ClientId", "RiskQuestionId")
                        .IsUnique();

                    b.ToTable("RiskQuestionnaireResponses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.TaxSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CessPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RebateIncomeThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RebateMaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StandardDeduction")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Regime")
                        .IsUnique();

                    b.ToTable("TaxSettings");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.TaxSlab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerBound")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlabOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UpperBound")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Regime", "SlabOrder")
                        .IsUnique();

                    b.ToTable("TaxSlabs");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AccountAllocation", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Account", "Account")
                        .WithMany("Allocations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClass")
                        .WithMany("AccountAllocations")
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AssetClass");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClassCorrelation", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClassA")
                        .WithMany()
                        .HasForeignKey("AssetClassAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.AssetClass", "AssetClassB")
                        .WithMany()
                        .HasForeignKey("AssetClassBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetClassA");

                    b.Navigation("AssetClassB");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Client", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Plan", "Plan")
                        .WithMany("Clients")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Expense", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Plan", "Plan")
                        .WithMany("Expenses")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.ExternalLogin", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Plan", "Plan")
                        .WithMany("Goals")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.GoalAccountLink", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Account", "Account")
                        .WithMany("GoalLinks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Goal", "Goal")
                        .WithMany("AccountLinks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Income", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("Incomes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Plan", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "PrimaryClient")
                        .WithMany()
                        .HasForeignKey("PrimaryClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryClient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany("Options")
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskQuestion");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestionnaireResponse", b =>
                {
                    b.HasOne("GoalsPlanningSystem.Domain.Entities.Client", "Client")
                        .WithMany("RiskQuestionnaireResponses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany()
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalsPlanningSystem.Domain.Entities.RiskQuestionOption", "RiskQuestionOption")
                        .WithMany()
                        .HasForeignKey("RiskQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("RiskQuestion");

                    b.Navigation("RiskQuestionOption");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Account", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("GoalLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Plans");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.AssetClass", b =>
                {
                    b.Navigation("AccountAllocations");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Client", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Incomes");

                    b.Navigation("RiskQuestionnaireResponses");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Goal", b =>
                {
                    b.Navigation("AccountLinks");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Expenses");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("GoalsPlanningSystem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
